### ISSUE TITLE
Release v0.2

### ISSUE THREAD

**Issue by kbarbary** [sep-developers/sep#12]
## To-do list for v0.2
- [x] C and Python `aperellip()` elliptical apertures with sub-pixel sampling
- [x] C and Python `aperellipann()` elliptical annulus
- [x] add background annulus to `sep.aperellip()`
- [x] add `sep.apercircann()` to Python interface.
- [x] tests vs Source Extractor MAG_AUTO.
- [x] "exact" mode aperture photometry from photutils.
- [x] `a`, `b`, `theta` parameters for ellipse functions.
- [x] New aperture photometry names? [#13]
- [x] Clean up and document flags, especially in Python interface.
- [x] update benchmarks.
- [x] aperture tests
- [x] `a`, `b`, `theta` parameters in `mask_ellipse` and `kron_radius`?
- [x] setable pixstack size?
- [x] `noise` -> `err`/`var` keywords in `extract()`
